export {
  type Affinity,
  type OffsetMap,
  type OffsetRange,
  type OffsetTransformResult,
  type NormalizedSourceMap,
  type ProjectionCapabilities,
  type ProjectionId,
  type ProjectionStage,
  type SourceLocation,
  type SourceMapPoint,
  type TransformMappingCapability,
  type TransformOffsetSpan,
  type TransformSpanMode,
  type TransformStep,
  type VirtualDocument,
  identityTransformMap,
  createIndentOffsetMap,
  createDedentOffsetMap,
  createEolOffsetMap,
  validateTransformMapping,
  composeOffsetMaps,
  mapTransformOffset,
  opaqueTransformMap,
  normalizeSourceMap,
  applyTransformMap,
  stageCapabilities,
  validateAnalysisTransform
} from "./index.js";
