version = 1

[build]
out_dir = ".ravel/build"

[[files]]
path = "live.md"
mode = "primary"

[[live.modules]]
specifier = "@example/csv"
from = "csv-parse/browser/esm/sync"

[[live.resources]]
name = "cool.csv"
path = "cool.csv"
